apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarqube-http
  namespace: sonarqube
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: sonarqube.k3s.wiserisk.be
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarqube-svc
                port:
                  number: 9000