apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hlabmonitor-http
  namespace: hlabmonitor
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: hlabmonitor.k3s.wiserisk.be
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hlabmonitor-svc
                port:
                  number: 8080