apiVersion: v1
kind: Service
metadata:
  labels:
    app: hlabmonitor
  name: hlabmonitor-svc
  namespace: hlabmonitor
spec:
  type: ClusterIP
  selector:
    app: hlabmonitor
  ports:
    - port: 8080