apiVersion: v1
kind: Service
metadata:
  labels:
    app: speedtest-exporter
  name: speedtest-exporter-svc
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: speedtest-exporter
  ports:
    - port: 9798