apiVersion: v2
name: sonarqube
description: SonarQube for K3S with Vault Plugin
type: application
version: 10.8.1
appVersion: v2.13.0
dependencies:
  - name: sonarqube
    version: 10.8.1
    repository: https://SonarSource.github.io/helm-chart-sonarqube