apiVersion: v2
name: sonarqube
description: SonarQube for K3S with Vault Plugin
type: application
version: 2025.6.1
appVersion: v2025.6.1
dependencies:
  - name: sonarqube
    version: 2025.6.1
    repository: https://SonarSource.github.io/helm-chart-sonarqube