community:
  enabled: true
persistence:
  enabled: true
  existingClaim: sonarqube-pvc
setAdminPassword:
  newPassword: <path:k3s/data/sonarqube#admin-password>
  currentPassword: admin
postgresql:
  enabled: false
monitoringPasscode: <path:k3s/data/sonarqube#monitoring-passcode>